import assert from 'node:assert/strict';
import fs from 'node:fs';
import zlib from 'node:zlib';
import { normalizeDecisionDate, normalizeDecisionDates } from '../ui/gh-pages-next/app/spending/decision-dates.mjs';
const sample = (decision_date, extra={}) => ({decision_date,source_snapshot_date:'2025-06-30',...extra});
assert.equal(normalizeDecisionDate(sample('0023-03-16')).decision_date,'2023-03-16');
assert.equal(normalizeDecisionDate(sample('0099-01-01')).decision_date,'1999-01-01');
assert.equal(normalizeDecisionDate(sample('2023-03-16')).decision_date,'2023-03-16');
assert.equal(normalizeDecisionDate(sample('0204-12-03')).decision_date,'0204-12-03');
const base='ui/gh-pages-next/public/spending/launch/';
const release=JSON.parse(fs.readFileSync(base+'latest.json'));
const rows=JSON.parse(zlib.gunzipSync(fs.readFileSync(base+release.release+'/awards.json.gz')));
const normalized=normalizeDecisionDates(rows);
assert.equal(normalized.filter(r=>r.decision_date_source).length,11);
assert.equal(normalized[0].decision_date,'2004-01-01');
assert.equal(normalized.at(-1).decision_date,'2025-06-30');
assert.equal(normalized.length,47397);
assert.equal(normalized.reduce((s,r)=>s+r.amount_cents,0),release.amount_cents);
assert.deepEqual(normalizeDecisionDates(normalized),normalized);
console.log('PASS: 11 date corrections; 47,397 rows and amounts unchanged; 0023 -> 2023; 0099 -> 1999; idempotent');
