import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const candidate = process.argv[3] === '--national-candidate' || (process.argv[3] === '--published-release' && JSON.parse(fs.readFileSync('ui/gh-pages-next/public/spending/launch/latest.json')).rows === 128837);
let workerUrl = new URL('../infra/cloudflare/spending-api/src/index.mjs', import.meta.url);
let temporary;
if (candidate) {
 temporary=fs.mkdtempSync(path.join(os.tmpdir(),'spending-candidate-api-'));
 const check=new DatabaseSync(process.argv[2],{readOnly:true});
 const meta=JSON.parse(check.prepare('SELECT payload FROM metadata WHERE id=1').get().payload);
 check.close();
 fs.copyFileSync(workerUrl,path.join(temporary,'index.mjs'));
 fs.writeFileSync(path.join(temporary,'release.json'),JSON.stringify(Object.fromEntries(
  ['version','release','rows','amount_cents','date_min','date_max','undated'].map(k=>[k,meta[k]]))));
 workerUrl=pathToFileURL(path.join(temporary,'index.mjs'));
 process.on('exit',()=>fs.rmSync(temporary,{recursive:true,force:true}));
}
const {respond}=await import(workerUrl);
const expected=candidate?{rows:128837,cents:8908050904021,galasa:11,galasaCents:572335676}:{rows:47397,cents:4865774429683,galasa:8,galasaCents:550596594};
if (!process.argv[2]) throw new Error('Pass the verify.db generated by build_spending_backend.mjs');
const db = new DatabaseSync(process.argv[2],{readOnly:true});
const env = {DB:{prepare(sql){return {args:[],bind(...args){this.args=args;return this;},async first(){return db.prepare(sql).get(...this.args);},async all(){return {results:db.prepare(sql).all(...this.args),meta:{rows_read:0}};}};},batch(stmts){return Promise.all(stmts.map(s=>s.all()));}}};
const get = async (path,params={}) => {const u=new URL(path,'https://example.test');for(const [k,v]of Object.entries(params))u.searchParams.set(k,v);return respond(new Request(u),env);};

const all=await (await get('/v1/awards')).json();
assert.equal(all.count,expected.rows);assert.equal(all.amount_cents,expected.cents);assert.equal(all.rows.length,12);
// The earliest candidate date is the literal 1925 value in the official source, not proof of historical coverage.
assert.equal(all.rows[0].decision_date,candidate?'1925-04-02':'2004-01-01');
assert.equal(all.undated_count,candidate?4:0);
const galasa=db.prepare("SELECT name FROM entities WHERE kind='authority' AND search LIKE '%consejer%galasa%'").get().name;
const filters={authority:galasa,start:'1999-01-01',end:'2027-12-31'};
const gal=await(await get('/v1/awards',filters)).json();assert.equal(gal.count,expected.galasa);assert.equal(gal.amount_cents,expected.galasaCents);
const jan=await(await get('/v1/awards',{...filters,start:'2025-01-01',end:'2025-01-31'})).json();assert.equal(jan.count,1);assert.equal(jan.amount_cents,754648);
const supplier=gal.rows[0].supplier;
const both=await(await get('/v1/awards',{...filters,supplier})).json();assert.ok(both.rows.every(r=>r.supplier===supplier));
const none=await(await get('/v1/awards',{authority:'No existe'})).json();assert.equal(none.count,0);
const out=await(await get('/v1/awards',{start:'2026-01-01',end:'2027-12-31',date_scope:'dated'})).json();assert.equal(out.count,0);
const selected=await(await get('/v1/awards',{start:'2023-03-16',end:'2023-03-16',q:'OBR/EMERG/2023/2244'})).json();assert.equal(selected.count,1);assert.equal(selected.rows[0].decision_date_source,'0023-03-16');
const opts=await(await get('/v1/options',{kind:'authority',q:'galasa'})).json();assert.ok(opts.values.includes(galasa));
assert.equal((await get('/v1/awards',{after:-1})).status,400);assert.equal((await get('/v1/awards',{limit:50000})).status,400);assert.equal((await get('/v1/awards',{start:'2025-02-30'})).status,400);assert.equal((await get('/v1/awards',{version:'old'})).status,400);
assert.equal((await respond(new Request('https://example.test/v1/awards',{method:'POST'}),env)).status,405);
assert.equal((await respond(new Request('https://example.test/v1/awards'),{DB:{prepare(){throw new Error('quota');}}})).status,503);
const unresolved=await(await get('/v1/awards',{date_scope:'unresolved',limit:200})).json();
assert.equal(unresolved.count,candidate?4:0);
assert.ok(unresolved.rows.every(row=>row.decision_date===null&&row.decision_date_status==='unresolved'&&/^0[2]/.test(row.decision_date_source)));
const dated=await(await get('/v1/awards',{date_scope:'dated'})).json();
assert.equal(dated.count+unresolved.count,expected.rows);
assert.equal(dated.amount_cents+unresolved.amount_cents,expected.cents);
const outsideWithUnknown=await(await get('/v1/awards',{start:'2026-01-01',end:'2027-12-31'})).json();
assert.equal(outsideWithUnknown.count,unresolved.count);
assert.equal((await get('/v1/awards',{date_scope:'invalid'})).status,400);
if(candidate){
 const authority=unresolved.rows[0].authority;
 const expectedUnknown=unresolved.rows.filter(r=>r.authority===authority);
 const filtered=await(await get('/v1/awards',{authority,date_scope:'unresolved'})).json();
 assert.equal(filtered.count,expectedUnknown.length);
 assert.equal(filtered.undated_count,expectedUnknown.length);
 const csvResponse=await get('/v1/export',{date_scope:'unresolved'});
 const text=await csvResponse.text();
 assert.equal(text.trim().split('\r\n').length,5);
 for(const row of unresolved.rows)assert.ok(text.includes(row.decision_date_source));
 assert.ok(text.includes('"decision_date_status"'));
}
let after=0,count=0,sum=0,corrections=0;const seen=new Set();
do {const r=await(await get('/v1/awards',{after,limit:200})).json();for(const row of r.rows){assert.ok(!seen.has(row.award_key));seen.add(row.award_key);count++;sum+=row.amount_cents;if(row.decision_date!==null&&row.decision_date_source!==row.decision_date)corrections++;}after=r.next_cursor;}while(after!==null);
assert.equal(count,expected.rows);assert.equal(sum,expected.cents);assert.ok(corrections>=11);assert.equal(corrections,candidate?15:11);
let csv='',cursor=0;
do{const r=await get('/v1/export',{...filters,after:cursor,limit:3});assert.equal(r.status,200);csv+=await r.text();const next=r.headers.get('X-Next-Cursor');cursor=next===''?null:Number(next);}while(cursor!==null);

assert.equal(csv.split('"decision_date_source"').length,2);
console.log(JSON.stringify({tests:'passed',rows:count,amount_cents:sum,date_corrections:corrections,galasa:gal.count,galasa_amount_cents:gal.amount_cents,first_response_bytes:JSON.stringify(all).length}));
