import assert from 'node:assert/strict';
import fs from 'node:fs';
import zlib from 'node:zlib';
import { normalizeDecisionDate, classifyDecisionDates } from '../ui/gh-pages-next/app/spending/decision-dates.mjs';
const sample = (decision_date, extra={}) => ({decision_date,source_snapshot_date:'2025-06-30',...extra});
assert.equal(normalizeDecisionDate(sample('0023-03-16')).decision_date,'2023-03-16');
assert.equal(normalizeDecisionDate(sample('0099-01-01')).decision_date,'1999-01-01');
assert.equal(normalizeDecisionDate(sample('2023-03-16')).decision_date,'2023-03-16');
assert.equal(normalizeDecisionDate(sample('0204-12-03')).decision_date,'0204-12-03');
const base='ui/gh-pages-next/public/spending/launch/';
const release=JSON.parse(fs.readFileSync(base+'latest.json'));
const parts=release.file_parts?.['awards.json']||[{path:'awards.json.gz'}];
const rows=JSON.parse(zlib.gunzipSync(Buffer.concat(parts.map(part=>fs.readFileSync(base+release.release+'/'+part.path)))));
const normalized=classifyDecisionDates(rows);
const candidate=release.rows===128837;
assert.equal(normalized.filter(r=>r.decision_date_status==='corrected').length,candidate?15:11);
assert.equal(normalized.filter(r=>r.decision_date_status==='unresolved').length,candidate?4:0);
assert.equal(normalized[0].decision_date,candidate?'1925-04-02':'2004-01-01');
assert.equal(normalized.filter(r=>r.decision_date!==null).at(-1).decision_date,'2025-06-30');
assert.equal(normalized.length,candidate?128837:47397);
assert.equal(normalized.reduce((s,r)=>s+r.amount_cents,0),release.amount_cents);
assert.deepEqual(classifyDecisionDates(normalized),normalized);
console.log(JSON.stringify({date_representation:'passed',rows:normalized.length,unresolved:candidate?4:0,corrections:candidate?15:11}));
