from __future__ import annotations

from pathlib import Path
from typing import Any

DEFAULT_DB = Path("etl/data/staging/politicos-es.db")
DEFAULT_SCHEMA = Path("etl/load/sqlite_schema.sql")
DEFAULT_RAW_DIR = Path("etl/data/raw")
DEFAULT_TIMEOUT = 45

BASE_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
}

SPAIN_COUNTRY_NAMES = {"spain", "espana", "españa", "es"}

# Minimal metadata per source. Extraction/normalization live in connector modules.
SOURCE_CONFIG: dict[str, dict[str, Any]] = {
    "congreso_diputados": {
        "name": "Congreso - Diputados Activos",
        "scope": "nacional",
        "default_url": "https://www.congreso.es/es/opendata/diputados",
        "format": "json",
        "institution_name": "Congreso de los Diputados",
        "level": "nacional",
        "role_title": "Diputado/a",
        # Guardrail for strict-network runs: ensures we didn't parse garbage/HTML.
        "min_records_loaded_strict": 300,
        "fallback_file": "etl/data/raw/samples/congreso_diputados_sample.json",
    },
    "cortes_aragon_diputados": {
        "name": "Cortes de Aragon - Diputados (XI Legislatura)",
        "scope": "autonomico",
        "default_url": (
            "https://www.cortesaragon.es/Quienes-somos.2250.0.html"
            "?no_cache=1&tx_t3comunicacion_pi3%5Bnumleg%5D=11"
            "&tx_t3comunicacion_pi3%5Btipinf%5D=3&tx_t3comunicacion_pi3%5Buidcom%5D=-2#verContenido"
        ),
        "format": "json",
        "institution_name": "Cortes de Aragon",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 50,
        "fallback_file": "etl/data/raw/samples/cortes_aragon_diputados_sample.json",
    },
    "senado_senadores": {
        "name": "Senado - Senadores",
        "scope": "nacional",
        "default_url": "https://www.senado.es/web/ficopendataservlet?tipoFich=6&legis=15",
        "format": "xml",
        "institution_name": "Senado de Espana",
        "level": "nacional",
        "role_title": "Senador/a",
        "min_records_loaded_strict": 250,
        "fallback_file": "etl/data/raw/samples/senado_senadores_sample.csv",
    },
    "europarl_meps": {
        "name": "Parlamento Europeo - MEPs",
        "scope": "europeo",
        "default_url": "https://www.europarl.europa.eu/meps/es/full-list/xml",
        "format": "xml",
        "institution_name": "Parlamento Europeo",
        "level": "europeo",
        "role_title": "Eurodiputado/a",
        "min_records_loaded_strict": 40,
        "fallback_file": "etl/data/raw/samples/europarl_meps_sample.xml",
    },
    "municipal_concejales": {
        "name": "Ambito municipal - Concejales y cargos locales",
        "scope": "municipal",
        "default_url": "https://concejales.redsara.es/consulta/getConcejalesLegislatura",
        "format": "xlsx",
        "institution_name": "Ayuntamiento",
        "level": "municipal",
        "role_title": "Cargo municipal",
        "min_records_loaded_strict": 50000,
        "fallback_file": "etl/data/raw/samples/municipal_concejales_sample.csv",
    },
    "asamblea_madrid_ocupaciones": {
        "name": "Asamblea de Madrid - Ocupaciones (cargos, incluidos diputados)",
        "scope": "autonomico",
        "default_url": "https://ctyp.asambleamadrid.es/static/doc/opendata/SGP_ADMIN.OPENDATA_OCUPACIONES_ASAMBLEA.csv",
        "format": "csv",
        "institution_name": "Asamblea de Madrid",
        "level": "autonomico",
        "role_title": "Cargo",
        "min_records_loaded_strict": 5000,
        "fallback_file": "etl/data/raw/samples/asamblea_madrid_ocupaciones_sample.csv",
    },
    "asamblea_ceuta_diputados": {
        "name": "Asamblea de Ceuta - Miembros (Legislatura 2023/2027)",
        "scope": "autonomico",
        "default_url": "https://www.ceuta.es/gobiernodeceuta/index.php/el-gobierno/la-asamblea",
        "format": "json",
        "institution_name": "Asamblea de Ceuta",
        "level": "autonomico",
        "role_title": "Diputado/a",
        "min_records_loaded_strict": 20,
        "fallback_file": "etl/data/raw/samples/asamblea_ceuta_diputados_sample.json",
    },
    "asamblea_melilla_diputados": {
        "name": "Asamblea de Melilla - Miembros (Legislatura 2023/2027)",
        "scope": "autonomico",
        "default_url": "https://sede.melilla.es/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS2_MIEMBROS",
        "format": "json",
        "institution_name": "Asamblea de Melilla",
        "level": "autonomico",
        "role_title": "Diputado/a",
        "min_records_loaded_strict": 20,
        "fallback_file": "etl/data/raw/samples/asamblea_melilla_diputados_sample.json",
    },
    "asamblea_extremadura_diputados": {
        "name": "Asamblea de Extremadura - Diputadas/os (XII Legislatura)",
        "scope": "autonomico",
        "default_url": "https://www.asambleaex.es/dipslegis",
        "format": "json",
        "institution_name": "Asamblea de Extremadura",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 50,
        "fallback_file": "etl/data/raw/samples/asamblea_extremadura_diputados_sample.json",
    },
    "asamblea_murcia_diputados": {
        "name": "Asamblea Regional de Murcia - Diputados",
        "scope": "autonomico",
        "default_url": "https://www.asambleamurcia.es/diputados",
        "format": "json",
        "institution_name": "Asamblea Regional de Murcia",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 35,
        "fallback_file": "etl/data/raw/samples/asamblea_murcia_diputados_sample.json",
    },
    "jgpa_diputados": {
        "name": "Junta General del Principado de Asturias - Diputados y diputadas",
        "scope": "autonomico",
        "default_url": "https://www.jgpa.es/diputados-y-diputadas",
        "format": "json",
        "institution_name": "Junta General del Principado de Asturias",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 35,
        "fallback_file": "etl/data/raw/samples/jgpa_diputados_sample.json",
    },
    "parlamento_canarias_diputados": {
        "name": "Parlamento de Canarias - Diputados (API)",
        "scope": "autonomico",
        "default_url": "https://parcan.es/api/diputados/por_legislatura/11/?format=json",
        "format": "json",
        "institution_name": "Parlamento de Canarias",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 60,
        "fallback_file": "etl/data/raw/samples/parlamento_canarias_diputados_sample.json",
    },
    "parlamento_cantabria_diputados": {
        "name": "Parlamento de Cantabria - Diputados (XI Legislatura)",
        "scope": "autonomico",
        "default_url": "https://parlamento-cantabria.es/informacion-general/composicion/11l-pleno-del-parlamento-de-cantabria",
        "format": "json",
        "institution_name": "Parlamento de Cantabria",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 25,
        "fallback_file": "etl/data/raw/samples/parlamento_cantabria_diputados_sample.json",
    },
    "parlament_balears_diputats": {
        "name": "Parlament de les Illes Balears - Diputats (webGTP)",
        "scope": "autonomico",
        "default_url": "https://www.parlamentib.es/Representants/Diputats.aspx?criteria=0",
        "format": "json",
        "institution_name": "Parlament de les Illes Balears",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 45,
        "fallback_file": "etl/data/raw/samples/parlament_balears_diputats_sample.json",
    },
    "parlamento_larioja_diputados": {
        "name": "Parlamento de La Rioja - Diputados (XI Legislatura)",
        "scope": "autonomico",
        "default_url": "https://adminweb.parlamento-larioja.org/composicion-y-organos/diputados",
        "format": "json",
        "institution_name": "Parlamento de La Rioja",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 25,
        "fallback_file": "etl/data/raw/samples/parlamento_larioja_diputados_sample.json",
    },
    "parlament_catalunya_diputats": {
        "name": "Parlament de Catalunya - Diputats (composicio actual)",
        "scope": "autonomico",
        "default_url": "https://www.parlament.cat/web/composicio/ple-parlament/composicio-actual/index.html",
        "format": "json",
        "institution_name": "Parlament de Catalunya",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 100,
        "fallback_file": "etl/data/raw/samples/parlament_catalunya_diputats_sample.json",
    },
    "corts_valencianes_diputats": {
        "name": "Les Corts Valencianes - Diputados (fichas HTML)",
        "scope": "autonomico",
        "default_url": "https://www.cortsvalencianes.es/es/composicion/diputados",
        "format": "json",
        "institution_name": "Les Corts Valencianes",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 70,
        "fallback_file": "etl/data/raw/samples/corts_valencianes_diputats_sample.json",
    },
    "cortes_clm_diputados": {
        "name": "Cortes de Castilla-La Mancha - Diputados (XI Legislatura)",
        "scope": "autonomico",
        "default_url": "https://www.cortesclm.es/web2/paginas/resul_diputados.php?legislatura=11",
        "format": "json",
        "institution_name": "Cortes de Castilla-La Mancha",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 25,
        "fallback_file": "etl/data/raw/samples/cortes_clm_diputados_sample.json",
    },
    "cortes_cyl_procuradores": {
        "name": "Cortes de Castilla y Leon - Procuradores y Procuradoras (XI Legislatura)",
        "scope": "autonomico",
        "default_url": "https://www.ccyl.es/Organizacion/PlenoAlfabetico",
        "format": "json",
        "institution_name": "Cortes de Castilla y Leon",
        "level": "autonomico",
        "role_title": "Procurador/a autonomico",
        "min_records_loaded_strict": 70,
        "fallback_file": "etl/data/raw/samples/cortes_cyl_procuradores_sample.json",
    },
    "parlamento_andalucia_diputados": {
        "name": "Parlamento de Andalucia - Diputados (fichas HTML)",
        "scope": "autonomico",
        "default_url": "https://www.parlamentodeandalucia.es/webdinamica/portal-web-parlamento/composicionyfuncionamiento/diputadosysenadores.do",
        "format": "json",
        "institution_name": "Parlamento de Andalucia",
        "level": "autonomico",
        "role_title": "Diputado/a autonomico",
        "min_records_loaded_strict": 90,
        "fallback_file": "etl/data/raw/samples/parlamento_andalucia_diputados_sample.json",
    },
    "parlamento_vasco_parlamentarios": {
        "name": "Parlamento Vasco - Parlamentarios (listado ACT)",
        "scope": "autonomico",
        "default_url": "https://www.legebiltzarra.eus/comparla/c_comparla_alf_ACT.html",
        "format": "json",
        "institution_name": "Parlamento Vasco",
        "level": "autonomico",
        "role_title": "Parlamentario/a autonomico",
        "min_records_loaded_strict": 60,
        "fallback_file": "etl/data/raw/samples/parlamento_vasco_parlamentarios_sample.json",
    },
    "parlamento_galicia_deputados": {
        "name": "Parlamento de Galicia - Deputados (fichas HTML)",
        "scope": "autonomico",
        "default_url": "https://www.parlamentodegalicia.gal/Composicion/Deputados",
        "format": "json",
        "institution_name": "Parlamento de Galicia",
        "level": "autonomico",
        "role_title": "Deputado/a autonomico",
        "min_records_loaded_strict": 50,
        "fallback_file": "etl/data/raw/samples/parlamento_galicia_deputados_sample.json",
    },
    "parlamento_navarra_parlamentarios_forales": {
        "name": "Parlamento de Navarra - Parlamentarios Forales (fichas HTML)",
        "scope": "autonomico",
        "default_url": "https://parlamentodenavarra.es/es/composicion-organos/parlamentarios-forales",
        "format": "json",
        "institution_name": "Parlamento de Navarra",
        "level": "autonomico",
        "role_title": "Parlamentario/a foral",
        "min_records_loaded_strict": 30,
        "fallback_file": "etl/data/raw/samples/parlamento_navarra_parlamentarios_forales_sample.json",
    },
}
