from __future__ import annotations

from .connectors import (
    AemetOpenDataSeriesConnector,
    AsambleaCeutaDiputadosConnector,
    AsambleaExtremaduraDiputadosConnector,
    AsambleaMelillaDiputadosConnector,
    AsambleaMadridOcupacionesConnector,
    AsambleaMurciaDiputadosConnector,
    BdnsApiSubvencionesConnector,
    BdnsAutonomicoConnector,
    BdeSeriesApiConnector,
    BoeApiLegalConnector,
    CongresoDiputadosConnector,
    CortesAragonDiputadosConnector,
    CortesClmDiputadosConnector,
    CortesCylProcuradoresConnector,
    CortsValencianesDiputatsConnector,
    EurostatSdmxConnector,
    EuroparlMepsConnector,
    JuntaGeneralAsturiasDiputadosConnector,
    MoncloaReferenciasConnector,
    MoncloaRssReferenciasConnector,
    MunicipalConcejalesConnector,
    ParlamentBalearsDiputatsConnector,
    ParlamentoCanariasDiputadosConnector,
    ParlamentoCantabriaDiputadosConnector,
    ParlamentoGaliciaDeputadosConnector,
    ParlamentoLaRiojaDiputadosConnector,
    ParlamentoNavarraParlamentariosForalesConnector,
    ParlamentCatalunyaDiputatsConnector,
    ParlamentoAndaluciaDiputadosConnector,
    ParlamentoVascoParlamentariosConnector,
    PlacspAutonomicoConnector,
    PlacspSindicacionConnector,
    SenadoSenadoresConnector,
)
from .connectors.base import BaseConnector


def get_connectors() -> dict[str, BaseConnector]:
    connectors: list[BaseConnector] = [
        CongresoDiputadosConnector(),
        SenadoSenadoresConnector(),
        EuroparlMepsConnector(),
        MunicipalConcejalesConnector(),
        AsambleaMadridOcupacionesConnector(),
        AsambleaCeutaDiputadosConnector(),
        AsambleaMelillaDiputadosConnector(),
        AsambleaExtremaduraDiputadosConnector(),
        AsambleaMurciaDiputadosConnector(),
        BoeApiLegalConnector(),
        JuntaGeneralAsturiasDiputadosConnector(),
        CortesAragonDiputadosConnector(),
        ParlamentBalearsDiputatsConnector(),
        ParlamentoCanariasDiputadosConnector(),
        ParlamentoCantabriaDiputadosConnector(),
        ParlamentoGaliciaDeputadosConnector(),
        ParlamentoLaRiojaDiputadosConnector(),
        ParlamentCatalunyaDiputatsConnector(),
        CortsValencianesDiputatsConnector(),
        CortesClmDiputadosConnector(),
        CortesCylProcuradoresConnector(),
        ParlamentoAndaluciaDiputadosConnector(),
        ParlamentoNavarraParlamentariosForalesConnector(),
        ParlamentoVascoParlamentariosConnector(),
        MoncloaReferenciasConnector(),
        MoncloaRssReferenciasConnector(),
        PlacspSindicacionConnector(),
        PlacspAutonomicoConnector(),
        BdnsApiSubvencionesConnector(),
        BdnsAutonomicoConnector(),
        EurostatSdmxConnector(),
        BdeSeriesApiConnector(),
        AemetOpenDataSeriesConnector(),
    ]
    return {c.source_id: c for c in connectors}
